#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
if [[$(xrandr -q | grep 'HDMI1 connected') ]]; then
    xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output HDMI1 --mode 1920x1080 --rotate normal --right-of eDP1

fi 

feh --bg-scale /home/uriel/Descargas/move.jpg
#trayer --edge top --align center --SetDockType true --SetPartialStrut true --expand true --width 10  --transparent  true  --alpha 0 --tint 0x292d3e --height 19 &

bspc monitor -d  I II III IV V  VI 7 8
bspc monitor HDMI1 -n 0 -d 9 10 11 

#$HOME/.config/polybar/launch.sh 
#$HOME/.config/lemonbar/launch
#trayer --edge top --align center --SetDockType true --SetPartialStrut true --expand true --width 10  --transparent  true  --alpha 0 --tint 0x292d3e --height 19

bspc rule -a emacs state=fullscreen
bspc rule -a Emacs state=tiled

bspc config border_width         0.7
bspc config window_gap           13
bspc config -n focused border_width 
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focs=on
bspc rule -a Screenkey manage=off
#bspc rule -a emacs state=fullscreen
#bspc rule -a Emacs split_ratio=0.25 border=off state=fullscreen
#bspc rule -a Emacs split_ratio=0.25 border=off state=fullscreen
#bspc rule -a Emacs:org-capture border=off state=floating
bspc rule -a discord follow=off
#export _JAVA_AWT_WM_NONREPARENTING=1ajosm
wmname LG3D
picom --config .config/picom/picom.conf &

#picom &
#dunst &
#yabar -c $HOME/.config/yabar/yabar.conf
$HOME/.config/polybar/launch.sh
#$HOME/.config/lemonbar/launch


